### ISSUE TITLE
K8s filebeat can't collect logs

### ISSUE THREAD

**Issue by xuhuigithub** [containers/oci-umount#26]
The default profile contains  /var/lib/docker/containers  that causes filebeat container can't mount volume from host /var/lib/docker/containers.

**Comment by rhatdan** [comment]
Why do they need to mount that volume?
@rhvgoyal Should we just mount /var/lib/docker/containers/* now?

**Comment by rhvgoyal** [comment]
By default we now have "/var/lib/docker/containers/*" in oci-umount.conf. And that means submounts of /var/lib/docker/containers/ will be unmounted.

So why volumes are being mounted with source being under /var/lib/docker/containers/. ?

**Comment by rhvgoyal** [comment]
/var/lib/docker/ directory is docker internal. And user should not be mounting anything there, nor user should use any part of it as source of the volume inside container.

**Comment by xuhuigithub** [comment]
IN Centos 7.2,When I yum update docker to 2:1.12.6-48.git0fdc778.el7.centos  this component will be installed by default,The machine was used as k8s compute node, and then I started the k8s official log collection container(a filebeat container ), which tried to mount the /var/lib/docker/containers directory to collect the other container logs within the cluster.
This is the official configuration file
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml

**Comment by xuhuigithub** [comment]
I think you might be able to delete it in your default configuration file, or hint at that in your README.md

**Comment by rhvgoyal** [comment]
@xuhuigithub ok, we had similar issue with fluentd container which tries to collect logs and bind mounts in /var/lib/docker/containers/.

We fixed it in later version of oci-umount where we changed it to `/var/lib/docker/containers/*` in /etc/oci-umount.conf by default. That means submounts of /var/lib/docker/containers/ will be unmounted but not the /var/lib/docker/containers/ itself.

So if you move to latest oci-umount, that should fix it.
