### ISSUE TITLE
umount error with crio - trident pod 

### ISSUE THREAD

**Issue by milind69** [containers/oci-umount#49]
I am trying to install netapps trident on CRIO + kubernetes cluster  I have installed 
oci-umount-2.3.4-2 cd 
the pod refused to go in running mode 
it runs if 
1) comment /var/lib/containers/storage/*

on my another instance I modified it to test 

2) to comment /var/lib/container/storage/* and /run/container/storage/* 
and added 
/var/lib/containers/storage/overlay/*
/var/lib/containers/storage/overlay-containers/*
/run/containers/storage/overlay/*
/run/containers/storage/overlay-containers/*

I am not sure which are the right settings I think option 1 is not right way , may be have to go with option 2 but put only right entries

inside container I see 
/var/lib/containers/storage/overlay  as overlay filesystem 
and
/run/containers/storage/overlay-containers as shm filesystem

**Comment by rhatdan** [comment]
You should not need oci-umount for this.  oci-umount is a program mainly targeted at removing leaked mounts usually from devivcemapper back end.  

I don't believe your issue is related to oci-umount.

**Comment by milind69** [comment]
But the pod went into running mode the moment we comment out the line ,
this was not only seen on one but two clusters I have. These are with CRIO

It did run cleanly on cri-containerd with rel version 20 without any
modifications but rel version 19 did fail in dry run.

**Comment by milind69** [comment]
does that mean i should unistall oci-umount rpm?

**Comment by rhatdan** [comment]
Yes I would not use this with overlay mounts.

**Comment by milind69** [comment]
Thanks
Rebuilding my cluster without it

**Comment by milind69** [comment]
removed oci-unmount from install , looks ok .. we can close this issue
